/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trvoid.modelmapper;

import org.modelmapper.ModelMapper;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public void test1() {
        ModelMapper modelMapper = new ModelMapper();

        SrcMessage src = new SrcMessage();
        src.setName("my-name");
        src.setType("10");
        src.setTitle("my-title");

        DstMessage dst = modelMapper.map(src, DstMessage.class);

        System.out.println(src);
        System.out.println(dst);
    }

    public static void main(String[] args) {
        App app = new App();

        System.out.println(app.getGreeting());

        app.test1();
    }
}
